[project]
name = "SigmaDictionary"
version = "0.1.0"
description = "Dictionary for true sigmas with level infinte aura."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "textual>=2.1.2",
]
